import type { Metadata, Viewport } from "next";

import { RevealBoot } from "@/components/Reveal";
import { fontClassNames } from "./fonts";
import "./globals.css";

const DESCRIPTION =
  "Hold one key, ask out loud, and Nimbus answers about whatever is on your screen — then moves your pointer to the exact thing it means. Seven-day free trial.";

export const metadata: Metadata = {
  // Just "Nimbus" in the tab. A browser tab is about 20 characters wide before it truncates, so a
  // tagline there is not a tagline — it is a name with rubbish after it. Sub-pages keep a short prefix
  // because "Nimbus" alone on four open tabs tells you nothing about which is which.
  title: {
    default: "Nimbus",
    template: "%s · Nimbus",
  },
  description: DESCRIPTION,
  applicationName: "Nimbus",
  metadataBase: new URL(process.env.SITE_URL ?? "https://nimbus.example"),
  openGraph: {
    // The long form belongs here, where a link preview has room for it.
    title: "Nimbus — ask about anything on your screen",
    description: DESCRIPTION,
    type: "website",
    siteName: "Nimbus",
    images: [{ url: "/nimbus_mark.png", width: 512, height: 512, alt: "Nimbus" }],
  },
  twitter: { card: "summary_large_image", description: DESCRIPTION },
  // Generated by `python -m tools.make_favicon`, which trims the mark and shifts it down 5.5% of the
  // canvas. A browser tab centres the icon geometrically next to text whose optical centre is lower, so a
  // mathematically centred mark reads as sitting high — and a tab is not a document, so CSS cannot fix it.
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "16x16 32x32 48x48" },
      { url: "/icon.png", type: "image/png", sizes: "180x180" },
    ],
    apple: "/icon.png",
  },
};

export const viewport: Viewport = {
  themeColor: "#0B0B0D",
  colorScheme: "dark",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    // `no-js` is removed by RevealBoot once React is running, so a failed bundle shows all the
    // content unanimated instead of a page of invisible elements.
    <html lang="en" className={`no-js ${fontClassNames}`}>
      <body className="min-h-dvh antialiased">
        <RevealBoot />
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-50 focus:rounded-md focus:bg-accent focus:px-4 focus:py-2 focus:font-semibold focus:text-[#1A0E04]"
        >
          Skip to content
        </a>
        {children}
      </body>
    </html>
  );
}
