import Image from "next/image";
import Link from "next/link";

import { Aurora, Spotlight } from "@/components/Atmosphere";
import { BuyButton } from "@/components/BuyButton";
import { Footer, Header } from "@/components/Chrome";
import { PointerDemo } from "@/components/PointerDemo";
import { ScreenWord } from "@/components/ScreenWord";
import { SectionHeading, StaggerGrid } from "@/components/Section";
import { KnowledgeStage } from "@/components/stages/KnowledgeStage";
import { PrivacyStage } from "@/components/stages/PrivacyStage";
import { QuizStage } from "@/components/stages/QuizStage";
import { Stage } from "@/components/stages/Stage";
import { TeachingStage } from "@/components/stages/TeachingStage";
import { Headline, Magnetic, Scramble } from "@/components/Type";
import { readSession } from "@/lib/auth";
import { DEFAULT_SEATS, TRIAL_DAYS } from "@/lib/licence";
import { stripeConfigured } from "@/lib/stripe";
import { manualTransferAvailable } from "@/lib/easypaisa";

/**
 * The landing page.
 *
 * Six sections, one idea each: what it is, how it works, what it knows, privacy, the plan, and one
 * closing ask. A longer page is not a more convincing page — every extra section is another thing
 * between a reader and the download button.
 *
 * A server component. All the motion lives in small client components, so the text arrives in the first
 * HTML response: fast on a phone on mobile data, and readable if the JavaScript never arrives at all.
 */
/** A separator whose spacing is padding rather than whitespace, so nothing can collapse it. */
function Dot() {
  return (
    <span aria-hidden className="px-[0.45em] text-ink-3/70">
      &middot;
    </span>
  );
}

export default async function Home() {
  const session = await readSession();
  const cards = stripeConfigured();
  const local = manualTransferAvailable();

  return (
    <div className="grain-page">
      <Aurora />
      <Header />

      <main id="main" className="relative">
        {/* ── hero ─────────────────────────────────────────────────────────── */}
        <section className="relative">
          {/*
           * The backdrop: a rendered image, not CSS.
           *
           * Generated by `python -m tools.make_backdrop` — a perspective floor, a warm key light, eleven
           * volumetric rays and baked grain, composited at 1920x1200 and saved as WebP. 13 KB, because
           * smooth gradients are the one thing WebP is exceptional at.
           *
           * The reason it is an image at all: procedural gradients look procedural. Three blurred circles
           * read as three blurred circles however slowly they drift, whereas a render can have a light
           * source, a receding surface and atmospheric falloff baked together. This is the same trade
           * Resend's landing page makes, at a twentieth of the file size.
           */}
          <div aria-hidden className="pointer-events-none absolute inset-0 -z-[5] overflow-hidden">
            <Image
              src="/hero-backdrop.webp"
              alt=""
              fill
              priority
              sizes="100vw"
              className="object-cover object-top opacity-90"
            />
            {/* Fades the render into the page colour, so there is no visible edge where it ends. */}
            <div className="absolute inset-x-0 bottom-0 h-56 bg-gradient-to-b from-transparent to-base" />
          </div>

          <div className="mx-auto max-w-6xl px-6 pb-16 pt-20 sm:pt-28">
          <div className="grid items-center gap-16 lg:grid-cols-[1.04fr_1fr]">
            <div>
              <div className="mb-7 inline-flex items-center gap-2.5 rounded-full border border-line-strong bg-elevated/60 py-1.5 pl-2 pr-4 backdrop-blur">
                <span className="rounded-full bg-accent/15 px-2 py-0.5 font-mono text-[11px] font-medium tracking-wide text-accent">
                  WINDOWS
                </span>
                <span className="text-[13.5px] text-ink-2">
                  {TRIAL_DAYS} days free, no card
                </span>
              </div>

              <h1 className="text-[clamp(2.1rem,5.6vw,4.15rem)]">
                <span className="block">
                  <Headline text="Ask about anything on your" />{" "}
                  <ScreenWord />
                </span>
                {/* A little more air than the rest of the headline's leading: the monitor's stand
                    occupies the space under the first line, and a tight gap put the two in contact. */}
                <span className="mt-3 block text-ink-3 sm:mt-4">
                  <Headline text="Out loud." delay={620} />
                </span>
              </h1>

              <p className="mt-7 max-w-xl text-[1.02rem] leading-relaxed text-ink-2 sm:text-[1.09rem]">
                Hold one key and ask, in the words you already have. Nimbus reads the screen in front of
                you, answers out loud, and takes your pointer to the exact thing it means.
              </p>

              <p className="mt-5 font-mono text-[13px] text-ink-3 sm:text-[14px]">
                <Scramble text="no tutorial / no screenshots / no describing it" />
              </p>

              <div className="mt-9 flex flex-wrap items-center gap-3.5">
                <Magnetic strength={7}>
                  <Link href="/download" prefetch={false} className="btn btn-primary">
                    <span>Download for Windows</span>
                  </Link>
                </Magnetic>
                <Link href="#how" className="btn">
                  <span>Watch it work</span>
                </Link>
              </div>

              {/* The separator is a styled element with real padding, not a character between spaces.
                  JSX collapses whitespace between a text node and an expression, so
                  `trial &middot; {SEATS}` rendered as "trial·2"; non-breaking spaces fixed that but are
                  still invisible in source and easy for a later edit to lose. Padding cannot be
                  collapsed by anything. */}
              <p className="mt-5 text-[13.5px] text-ink-3 sm:text-[14px]">
                Free while Nimbus is in development
                <Dot />
                {DEFAULT_SEATS} devices
                <Dot />
                no card, nothing to cancel
              </p>
            </div>

            <PointerDemo />
            </div>
          </div>
        </section>

        {/* ── how ──────────────────────────────────────────────────────────── */}
        <section id="how" className="mx-auto max-w-6xl scroll-mt-24 px-6 py-[clamp(3.5rem,9vw,var(--space-section))]">
          <SectionHeading
            eyebrow="How it works"
            title="Three keys, and the words you already have"
            lead="No copying a screenshot into a chat window. No working out what the thing you are looking at is called."
          />

          <StaggerGrid className="mt-[var(--space-lead-content)] grid gap-4 sm:grid-cols-3">
            {[
              {
                step: "01",
                title: "Hold the key",
                body: "Ctrl + Alt + Space, in any application. Nimbus listens while you hold it and stops the moment you let go.",
              },
              {
                step: "02",
                title: "Ask it roughly",
                body: "\u201cWhat is this for?\u201d \u201cWhy did that fail?\u201d \u201cWhat do I do next?\u201d You do not need the right words. It can see what you can see.",
              },
              {
                // Trimmed to roughly the length of the other two. It was nearly twice as long, which
                // made the third card taller than its neighbours and the row look broken.
                step: "03",
                title: "Get walked through it",
                body: "You hear the answer as your pointer arrives on the control. More than one step? It draws them in order.",
              },
            ].map((card) => (
              <Spotlight key={card.step} className="rounded-[12px]">
                <article className="surface surface-hover grain h-full p-6 sm:p-7">
                  <p className="font-mono text-[13px] text-accent">{card.step}</p>
                  <h3 className="mt-4 text-[1.15rem]">{card.title}</h3>
                  <p className="mt-2.5 text-[0.99rem] leading-relaxed text-ink-2">{card.body}</p>
                </article>
              </Spotlight>
            ))}
          </StaggerGrid>
        </section>

        {/* ── the four stage sets ──────────────────────────────────────────
         *
         * Each of these shows the feature working instead of describing it. That is the whole structural
         * lesson from the reference: a section that claims something is a paragraph, and a section that
         * performs it is evidence. They are the most expensive things on this page and the reason to
         * scroll past the hero.
         *
         * `Stage` keeps the layout identical across all four so they read as one product, and alternates
         * which side the copy sits on so the page does not become a column of captioned pictures.
         */}
        <section id="built" className="scroll-mt-24">
          <Stage
            eyebrow="Teaching mode"
            title="It draws the steps on your screen"
            lead="When the answer is more than one click, Nimbus dims everything else, numbers what to touch and in what order, then draws an arrow from the thing that went wrong to the thing that fixes it."
            demo={<TeachingStage />}
          />

          <Stage
            reverse
            eyebrow="Your own software"
            title="It reads the notes you drop in a folder"
            lead="Name a Markdown file after the executable and Nimbus treats it as authoritative for that program. It quotes your own note back and tells you which file it came from, so you can check it."
            demo={<KnowledgeStage />}
          />

          <Stage
            eyebrow="Privacy Guard"
            title="It refuses to look, and shows you the count"
            lead="With a password manager or a sign-in page in front, the screenshot does not happen. You still get an answer, and the number on Home goes up. That number is the point: an observation is worth more than a promise."
            demo={<PrivacyStage />}
          />

          {/* `lead` is a JSX *string attribute*, where `\u201c` is not an escape sequence — it renders
              literally, which is exactly what happened here. Real characters, or a `{"..."}` expression.
              `wide` gives this demo more of the row, because it has two panels of text to fit. */}
          <Stage
            reverse
            wide
            eyebrow="Quiz me"
            title="It asks you, against the screen you are on"
            lead={
              "Say \u201cquiz me\u201d and the questions come the other way. Get one wrong and it does " +
              "not mark you down \u2014 it points at where the answer is. A flashcard app cannot see " +
              "what you are working on."
            }
            demo={<QuizStage />}
          />
        </section>

        {/* ── the dense grid ──────────────────────────────────────────────── */}
        <section className="mx-auto max-w-6xl px-6 py-[clamp(3.5rem,9vw,var(--space-section))]">
          <SectionHeading
            eyebrow="Everything else"
            title="The rest of what is in there"
            lead="Built over four tiers of work, and most of it exists because a real session needed it."
          />

          <StaggerGrid className="mt-[var(--space-lead-content)] grid gap-x-8 gap-y-7 sm:grid-cols-2 lg:grid-cols-3">
            {[
              {
                title: "Runs fully offline",
                body: "Model, speech recognition and voice all local. No API key, nothing leaving the machine.",
              },
              {
                title: "Bring your own key",
                body: "Gemini by default, or OpenAI, Anthropic and Ollama. Keys live in Windows Credential Manager.",
              },
              {
                title: "Per-application memory",
                body: "Plain Markdown per executable, with a local index. Readable, editable, deletable.",
              },
              {
                title: "Knowledge journal",
                body: "What you have been asking about, collected into something you can review later.",
              },
              {
                title: "Session export",
                body: "One click writes the whole session to a timestamped Markdown file, memory included.",
              },
              {
                title: "Chat panel, uncapturable",
                body: "Excluded from screen capture at the OS level, so it cannot appear in a screen share.",
              },
              {
                title: "Remap the hotkey",
                body: "Any chord you like. Record it in Settings; the window stops the chord pressing its own buttons.",
              },
              {
                title: "14-day offline grace",
                body: "A cached licence keeps working on a flight. A tool that stops working offline is worse than one that gets shared.",
              },
              {
                title: "Update check on launch",
                body: "Asynchronous, and it never blocks startup. It offers, it does not interrupt.",
              },
            ].map((item) => (
              <div key={item.title} className="relative pl-5">
                <span
                  aria-hidden
                  className="absolute left-0 top-[0.55rem] h-1.5 w-1.5 rounded-full bg-accent"
                />
                <h3 className="text-[1.02rem]">{item.title}</h3>
                <p className="mt-1.5 text-[0.94rem] leading-relaxed text-ink-2">{item.body}</p>
              </div>
            ))}
          </StaggerGrid>
        </section>

        {/* ── privacy ──────────────────────────────────────────────────────── */}
        <section id="privacy" className="mx-auto max-w-6xl scroll-mt-24 px-6 py-[clamp(3.5rem,9vw,var(--space-section))]">
          <SectionHeading
            eyebrow="Privacy"
            title="An assistant that looks at your screen has to earn that"
            lead="Four decisions we made early, when they were still cheap to make. Each one is a behaviour you can check rather than a policy you have to take on trust."
          />

          <StaggerGrid className="mt-[var(--space-lead-content)] grid gap-4 lg:grid-cols-2">
            {[
              {
                title: "It refuses to look",
                body: "With a password manager or a sign-in page in front, Nimbus answers without taking a screenshot at all, and shows you a running count of every time it has done that. A count is an observation. A promise is not.",
              },
              {
                title: "Your keys never leave your machine",
                body: "They live in Windows Credential Manager, and Nimbus has no server that can read them. The account exists to bind your licence to your devices and nothing else \u2014 no telemetry, no screen contents, no keys.",
              },
              {
                title: "Your conversation cannot be screenshotted",
                body: "The chat panel is excluded from screen capture by the operating system, so it cannot appear in a screenshot or a screen share, including one Nimbus takes itself.",
              },
              {
                title: "We store a hash, not your hardware",
                body: "Counting your devices needs to tell them apart, so the app sends a salted hash of the machine. Never a raw identifier, and nothing that correlates outside Nimbus.",
              },
            ].map((card, index) => (
              <Spotlight key={card.title} className="rounded-[12px]">
                <article className="surface grain flex h-full flex-col border-l-2 border-l-accent/50 p-6 sm:p-7">
                  <div className="flex items-baseline gap-3">
                    <span className="font-mono text-[13px] text-accent">0{index + 1}</span>
                    <h3 className="text-[1.12rem]">{card.title}</h3>
                  </div>
                  <p className="mt-3 text-[0.99rem] leading-relaxed text-ink-2">{card.body}</p>
                </article>
              </Spotlight>
            ))}
          </StaggerGrid>
        </section>

        {/* ── pricing ──────────────────────────────────────────────────────── */}
        <section id="pricing" className="mx-auto max-w-6xl scroll-mt-24 px-6 py-[clamp(3.5rem,9vw,var(--space-section))]">
          <SectionHeading
            eyebrow="The plan"
            title="One plan, and nothing held back"
            lead="No tiers, no seats you have to count, nothing kept behind a higher plan. Nimbus is a personal project and billing is not switched on, so there is nothing to pay."
          />

          <div className="mt-[var(--space-lead-content)] grid gap-4 lg:grid-cols-[1.15fr_1fr]">
            <Spotlight className="rounded-[12px]">
              <div className="surface grain h-full p-6 sm:p-8">
                <p className="eyebrow">Nimbus</p>
                <p className="mt-3 flex items-baseline gap-2.5">
                  <span className="shine font-display text-[3.4rem] font-semibold tracking-[-0.04em]">
                    Free
                  </span>
                  <span className="text-ink-2">while it is in development</span>
                </p>

                <ul className="mt-7 space-y-3">
                  {[
                    `A ${TRIAL_DAYS}-day licence to start, no card`,
                    `Up to ${DEFAULT_SEATS} of your own devices`,
                    "Bring your own model key, or run it fully offline",
                    "Every feature from the first day",
                  ].map((item) => (
                    <li key={item} className="flex gap-3 text-ink-2">
                      <span aria-hidden className="mt-0.5 font-semibold text-accent">
                        &#10003;
                      </span>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>

                <div className="mt-8 flex flex-wrap items-center gap-3.5">
                  <Magnetic strength={6}>
                    <Link href="/download" prefetch={false} className="btn btn-primary">
                      <span>Start free</span>
                    </Link>
                  </Magnetic>
                  <BuyButton signedIn={Boolean(session)} cardsEnabled={cards} />
                </div>
                <p className="mt-5 text-[13.5px] text-ink-3">
                  Create an account, and your licence key is emailed to you and kept on your account
                  page. You will not have to go looking for it.
                </p>
              </div>
            </Spotlight>

            <Spotlight className="rounded-[12px]">
              <div className="surface grain h-full p-6 sm:p-8">
                <p className="eyebrow">Bank transfer</p>
                <h3 className="mt-3.5 text-[1.28rem]">Built, but not switched on</h3>
                <p className="mt-3 leading-relaxed text-ink-2">
                  A card rail and a transfer rail are both implemented and covered by tests, because
                  device-bound licensing was a problem worth solving properly. Neither is connected:
                  nothing is charged and no payment has ever been taken.
                </p>
                {local ? (
                  <p className="mt-5 leading-relaxed text-ink-2">
                    The transfer flow is the interesting half &mdash; a reference from a receipt,
                    checked by hand rather than by a webhook. You can read how it works.
                  </p>
                ) : null}
                <div className="mt-8">
                  <Link href="/pay" className="btn">
                    <span>How the transfer rail works</span>
                  </Link>
                </div>
                <p className="mt-5 text-[13.5px] text-ink-3">
                  Every feature is available to everyone, on all {DEFAULT_SEATS} devices.
                </p>
              </div>
            </Spotlight>
          </div>
        </section>

        {/* ── close ──────────────────────────────────────────────────────────
         *
         * No card, no grain, no spotlight: this sits directly on the page background. Every other section
         * is content inside a container, so ending on bare page makes the last thing you read feel like
         * the page talking rather than one more panel — and it lets the backdrop's own light be the
         * texture instead of competing with a surface.
         */}
        <section className="mx-auto max-w-6xl px-6 pb-8">
          <div>
            <div className="px-2 py-14 text-center sm:py-20">
              <Headline
                as="h2"
                whenVisible
                text="Try it on whatever has you *stuck* right now"
                className="mx-auto block max-w-2xl text-[clamp(1.5rem,3.2vw,2.3rem)]"
              />
              <p className="mx-auto mt-5 max-w-lg leading-relaxed text-ink-2">
                {TRIAL_DAYS} days, no card. If it has not earned a place on your machine within a week,
                it never will.
              </p>
              <div className="mt-9 flex flex-wrap justify-center gap-3.5">
                <Magnetic strength={7}>
                  <Link href="/download" prefetch={false} className="btn btn-primary">
                    <span>Download for Windows</span>
                  </Link>
                </Magnetic>
                <Link href="/signup" className="btn">
                  <span>Create an account</span>
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
