"""Render the hero backdrop for the website.

    python -m tools.make_backdrop

Writes ``web/public/hero-backdrop.webp``.

## Why a rendered image instead of CSS

The reference for this page is Resend's landing page, and the interesting thing about it is that its
"3D" is not 3D at all: two raster images do the whole atmosphere -- a floor plane and a light-ray pass,
served as a JPEG and a PNG. No WebGL, no canvas, no shader.

That is the right trade for us too, and for a sharper reason than fashion. Procedural CSS gradients look
procedural: three blurred circles read as three blurred circles however slowly they drift. A rendered
image can have a light source, a receding floor, atmospheric falloff and film grain baked together, and
it costs one request that the browser decodes off the main thread.

It is generated by this script rather than drawn by hand so it is reproducible, reviewable, and honestly
ours -- and so the palette comes from `theme.py` rather than from someone's eyedropper.

## What it draws, bottom to top

1. A vertical base wash: near-black, warming very slightly toward the horizon.
2. A perspective floor -- lines converging on a vanishing point, spacing growing geometrically, fading
   with distance. This is what creates depth; everything else is light on top of it.
3. A warm key light above and left of centre, as a wide radial falloff.
4. Volumetric rays from the key light, each a soft-edged wedge, blurred heavily and composited additively
   so overlaps brighten.
5. A horizon glow where the floor meets the dark.
6. A vignette, then per-pixel grain -- the same idea as the app's `GrainOverlay`, baked in at render time
   so the page does not have to composite it live.
"""
from __future__ import annotations

import math
import random
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "web" / "public" / "hero-backdrop.webp"

WIDTH, HEIGHT = 1920, 1200
"""Rendered at 1920 wide because that is what the hero occupies on a large display, and downscaling in
the browser is free while upscaling is not. 1200 tall covers a 16:10 hero without letterboxing."""

# From theme.py. Not eyeballed.
BG_BASE = (11, 11, 13)
ACCENT = (255, 122, 26)
ACCENT_DEEP = (217, 96, 10)

HORIZON = int(HEIGHT * 0.52)
"""Where the floor starts. Slightly above centre, so the composition has more floor than sky -- the
hero's text sits in the upper half and wants the quieter area behind it."""

LIGHT = (int(WIDTH * 0.38), int(HEIGHT * 0.14))
"""The key light: above and left of centre, so the rays fall diagonally across the text rather than
symmetrically behind it. Symmetry here reads as a stock gradient."""


def base_wash() -> Image.Image:
    """A vertical gradient, warming a touch toward the horizon."""
    image = Image.new("RGB", (1, HEIGHT))
    pixels = image.load()
    for y in range(HEIGHT):
        distance = abs(y - HORIZON) / HEIGHT
        warmth = max(0.0, 1.0 - distance * 3.2)
        pixels[0, y] = (
            int(BG_BASE[0] + 26 * warmth),
            int(BG_BASE[1] + 14 * warmth),
            int(BG_BASE[2] + 8 * warmth),
        )
    return image.resize((WIDTH, HEIGHT), Image.BILINEAR)


def floor_plane() -> Image.Image:
    """A perspective grid below the horizon: the thing that actually creates depth.

    Verticals converge on a vanishing point directly under the light, which keeps the geometry consistent
    with where the illumination comes from. Horizontals are spaced geometrically -- each one closer to the
    viewer than the last by a growing margin -- because that is what perspective does, and an evenly
    spaced set of lines reads as a flat pattern rather than as a receding surface.
    """
    layer = Image.new("L", (WIDTH, HEIGHT), 0)
    draw = ImageDraw.Draw(layer)
    vanishing = (LIGHT[0], HORIZON)

    # Verticals, fanned out well past the frame so the outermost ones still cross it near the bottom.
    for index in range(-34, 35):
        offset = index * (WIDTH / 13)
        draw.line(
            [vanishing, (vanishing[0] + offset * 3.1, HEIGHT + 220)],
            fill=64,
            width=2,
        )

    # Horizontals. `1.34 ** n` puts the first few tight to the horizon and the last few far apart.
    row, step = 0.0, 5.0
    while HORIZON + row < HEIGHT + 120:
        y = int(HORIZON + row)
        strength = min(150, int(26 + row * 0.22))
        draw.line([(0, y), (WIDTH, y)], fill=strength, width=2 if row > 90 else 1)
        row += step
        step *= 1.34

    # Fade the grid out toward the horizon, where a real floor loses contrast to atmosphere.
    fade = Image.new("L", (1, HEIGHT), 0)
    fade_pixels = fade.load()
    for y in range(HEIGHT):
        if y < HORIZON:
            fade_pixels[0, y] = 0
        else:
            depth = (y - HORIZON) / max(1, HEIGHT - HORIZON)
            fade_pixels[0, y] = int(255 * min(1.0, depth * 1.9) * (1.0 - depth * 0.45))
    layer = Image.composite(layer, Image.new("L", layer.size, 0), fade.resize(layer.size, Image.BILINEAR))
    return layer.filter(ImageFilter.GaussianBlur(0.6))


def radial(centre: tuple[int, int], radius: int, peak: int = 255) -> Image.Image:
    """A soft radial falloff, drawn small and scaled up -- cheap, and smoother than a per-pixel loop."""
    size = 256
    small = Image.new("L", (size, size), 0)
    draw = ImageDraw.Draw(small)
    for step in range(size // 2, 0, -1):
        value = int(peak * (1.0 - step / (size / 2)) ** 2.1)
        draw.ellipse(
            [size / 2 - step, size / 2 - step, size / 2 + step, size / 2 + step],
            fill=value,
        )
    small = small.filter(ImageFilter.GaussianBlur(6))
    canvas = Image.new("L", (WIDTH, HEIGHT), 0)
    scaled = small.resize((radius * 2, radius * 2), Image.BICUBIC)
    canvas.paste(scaled, (centre[0] - radius, centre[1] - radius), scaled)
    return canvas


def light_rays() -> Image.Image:
    """Volumetric wedges from the key light, blurred and composited additively.

    Additive rather than a plain paste so crossing rays brighten each other, which is what makes them read
    as light in air rather than as translucent triangles.
    """
    layer = Image.new("L", (WIDTH, HEIGHT), 0)
    random.seed(7)  # Deterministic: the same backdrop every time this runs.

    from PIL import ImageChops

    for index in range(11):
        wedge = Image.new("L", (WIDTH, HEIGHT), 0)
        draw = ImageDraw.Draw(wedge)
        # Fanned across the lower-right quadrant: the light is up and left, so the rays travel down and
        # across the frame rather than straight down, which would read as a curtain.
        angle = math.radians(52 + index * 8.2 + random.uniform(-2.2, 2.2))
        spread = math.radians(random.uniform(1.1, 2.8))
        length = HEIGHT * random.uniform(1.3, 1.9)
        brightness = int(random.uniform(90, 190))

        draw.polygon(
            [
                LIGHT,
                (
                    LIGHT[0] + math.cos(angle - spread) * length,
                    LIGHT[1] + math.sin(angle - spread) * length,
                ),
                (
                    LIGHT[0] + math.cos(angle + spread) * length,
                    LIGHT[1] + math.sin(angle + spread) * length,
                ),
            ],
            fill=brightness,
        )
        wedge = wedge.filter(ImageFilter.GaussianBlur(random.uniform(30, 70)))
        # `lighter`, not `blend`. Blending averaged each new wedge with the accumulated total, so eleven
        # rays ended up dimmer than one -- and the multiplier I used to compensate was guesswork.
        # Taking the brighter of the two accumulates properly and cannot overflow.
        layer = ImageChops.lighter(layer, wedge)

    return layer.filter(ImageFilter.GaussianBlur(20))


def tint(mask: Image.Image, colour: tuple[int, int, int], strength: float) -> Image.Image:
    """A coloured layer shaped by ``mask``, ready to screen onto the base."""
    flat = Image.new("RGB", (WIDTH, HEIGHT), colour)
    scaled = mask.point(lambda value: int(value * strength))
    return Image.composite(flat, Image.new("RGB", (WIDTH, HEIGHT), (0, 0, 0)), scaled)


def screen(base: Image.Image, layer: Image.Image) -> Image.Image:
    """Additive-ish blend. Light adds; it never darkens what is already there."""
    from PIL import ImageChops

    return ImageChops.screen(base, layer)


def vignette(image: Image.Image, floor: float = 0.52) -> Image.Image:
    """Darken the edges by *scaling*, never by subtracting.

    The first version subtracted a flat 30% white wherever the vignette mask was bright. On a backdrop
    whose values are mostly under 40, subtracting ~76 clamped everything outside the light's column to
    black — the render measured a mean of 8.5 with a standard deviation of 0.4 in the blue channel, which
    is another way of saying "an almost entirely black rectangle".

    Multiplying is the correct operation for shading: it scales what is there, so a dark area cannot go
    below zero and a bright area keeps its shape. ``floor`` is how bright the corners stay.
    """
    from PIL import ImageChops

    mask = radial((WIDTH // 2, int(HEIGHT * 0.44)), int(WIDTH * 0.82), peak=255)
    scale = mask.point(lambda value: int(255 * (floor + (1 - floor) * value / 255)))
    return ImageChops.multiply(image, Image.merge("RGB", (scale, scale, scale)))


def main() -> int:
    from PIL import ImageChops

    image = base_wash()

    # The floor, in a dim warm grey rather than pure white: a lit floor in a dark room is not white.
    image = screen(image, tint(floor_plane(), (168, 138, 112), 0.62))

    # The key light, then the rays, then the horizon glow.
    image = screen(image, tint(radial(LIGHT, int(WIDTH * 0.58)), ACCENT, 0.5))
    image = screen(image, tint(light_rays(), ACCENT, 0.42))
    image = screen(
        image,
        tint(radial((LIGHT[0], HORIZON), int(WIDTH * 0.38)), ACCENT_DEEP, 0.38),
    )

    image = vignette(image)

    # Grain, baked in. The app composites this live over its surfaces; here it costs nothing at runtime.
    random.seed(11)
    noise = Image.effect_noise((WIDTH, HEIGHT), 26).convert("L")
    image = ImageChops.blend(image, screen(image, tint(noise, (255, 245, 235), 0.13)), 0.55)

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    # Quality 80 with method 6: WebP's slowest, smallest setting. A backdrop is mostly smooth gradients,
    # which WebP handles far better than JPEG -- and unlike AVIF it needs no extra Pillow plugin.
    image.save(TARGET, "WEBP", quality=80, method=6)

    size_kb = TARGET.stat().st_size / 1024
    print(f"Wrote {TARGET.relative_to(ROOT)}  {WIDTH}x{HEIGHT}  {size_kb:,.0f} KB")
    if size_kb > 400:
        print("  WARNING: over 400 KB. Drop quality or dimensions -- this loads in the hero.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
