; Inno Setup script for Nimbus.
;
; Wraps the PyInstaller --onedir output (dist/Nimbus/) into a single
; Setup.exe for distribution via GitHub Releases.
;
; Per-user install — no UAC prompt, lower friction on locked-down machines.
;
; Build:
;     iscc installer\nimbus.iss
;
; Output: installer\Output\Nimbus-Windows-Setup-v<version>.exe (~125-170 MB
; after Inno's LZMA2 compresses the onedir bundle, including the local stack).
;
; Inno Setup 6+ required: https://jrsoftware.org/isdl.php (free).

#define AppName "Nimbus"
#ifndef AppVersion
#define AppVersion "1.0.0"
#endif
; "The Nimbus Authors" was the MIT copyright line and outlived it -- the licence is proprietary now,
; and this string is what Windows shows in Apps & features and on the UAC publisher field.
#define AppPublisher "Nimbus"

; The website, not the repository. This feeds AppPublisherURL and AppSupportURL, which are links a
; *user* clicks from Windows' own settings, and the website is where they came from. It has twice been
; pointed at a repository that could not serve them: once at a name that had been renamed, once at one
; that was private. Both 404'd for every user.
#define AppURL "https://trynimbus.vercel.app"

; Updates are a SEPARATE URL from the website, and that is not tidiness.
;
; This was `{#AppURL}/releases`, and the site has no such route -- there is no `/releases` page and no
; rewrite for one, so the "check for updates" link in Apps & features was a 404 for every installed
; copy. Releases live in a public repository rather than on the site, which is the same target
; `updates.REPOSITORY` checks, so the two cannot disagree about where a new version comes from.
#define AppUpdatesURLValue "https://github.com/ArhamKhan117/Nimbus/releases"
#define AppExeName "Nimbus.exe"

[Setup]
AppId={{C9A8F1B3-7D2E-4A6F-9E8C-3B1D5F2A4C8D}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}
AppUpdatesURL={#AppUpdatesURLValue}
; Per-user install — no admin/UAC required. {userpf} = %LOCALAPPDATA%\Programs
DefaultDirName={userpf}\{#AppName}
DefaultGroupName={#AppName}
; PrivilegesRequired=lowest avoids the elevation prompt; auto means
; per-user-or-system based on whether the user is admin (we want
; per-user always).
PrivilegesRequired=lowest
OutputDir=Output
OutputBaseFilename=Nimbus-Windows-Setup-v{#AppVersion}
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
DisableProgramGroupPage=yes
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
LicenseFile=..\LICENSE
; Show "Run Nimbus" checkbox on final wizard page.
SetupLogging=yes
UninstallDisplayName={#AppName}
UninstallDisplayIcon={app}\{#AppExeName}

; --- Branding ---------------------------------------------------------------
;
; The setup executable's own icon, and the wizard's imagery. Without these the
; installer is a generic Inno Setup window with a blue stock banner, which is
; the first thing a user sees of the product.
;
; All three come from assets/, generated by `python -m tools.make_icons` from
; the same orange mark the application uses -- so the setup icon, the installed
; app icon and the in-app logo cannot drift apart.
SetupIconFile=..\assets\nimbus_tray.ico
; 164x314 side banner on the welcome and finish pages, on the Nimbus dark
; background rather than Inno's white stock image.
WizardImageFile=..\assets\nimbus_installer.png
WizardImageStretch=no
; The small header icon shown on every other page. The cursor mark reads better
; than the full logo at 55x55 -- it is a single silhouette rather than a lockup,
; so it survives being that small where the wordmark version would not.
WizardSmallImageFile=..\assets\nimbus_installer_small.png

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional shortcuts:"; Flags: unchecked

[Files]
; Bundle the entire PyInstaller --onedir output. recursesubdirs grabs
; the _internal/ tree (Qt plugins, Python stdlib, all bundled deps).
Source: "..\dist\Nimbus\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
; No IconFilename on the shortcuts that point at Nimbus.exe: Windows reads the
; icon from the executable's own PE resource, which nimbus.spec embeds from
; assets/nimbus_tray.ico. Naming a separate .ico here would be a second copy to
; keep in step, and the first one to go stale.
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppExeName}"
Name: "{group}\Open Knowledge Folder"; Filename: "{userdocs}\Nimbus Wiki"; Comment: "Drop per-app .md files here"; IconFilename: "{app}\_internal\assets\nimbus_tray.ico"
Name: "{group}\Uninstall {#AppName}"; Filename: "{uninstallexe}"
Name: "{userdesktop}\{#AppName}"; Filename: "{app}\{#AppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#AppExeName}"; Description: "Launch {#AppName}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
; Don't delete user data on uninstall — preserve memory + KB folders.
; If a user wants a clean wipe, they delete ~/.nimbus/ +
; ~/Documents/Nimbus Wiki/ manually. This matches the "transparency
; contract" UX: their data is theirs.
Type: filesandordirs; Name: "{app}\_internal\__pycache__"
